### ISSUE TITLE
Repeated calls to jump-char-forward don't reuse the search character

### ISSUE THREAD

**Issue by Wilfred** [lewang/jump-char#16]
Given a buffer:

```
|foo=1 bar=2 baz=3
```

and jump-char configured as follows:

```
(global-set-key (kbd "M-m") #'jump-char-forward)
```

I press `M-m = M-m`. I expect my cursor to be moved to the second equals sign. However, on the second `M-m` I'm prompted again. The docstring says:

> press current binding for `jump-char-forward' / `jump-char-backward' to reuse
> last input.

so I would expect repeated presses of `M-m` to just search for = without prompting. Have I misunderstood?

**Comment by lewang** [comment]
Have repro, will look into soon.

On Thu, Jan 8, 2015 at 10:08 AM, Wilfred Hughes <notifications@github.com>
wrote:

> Given a buffer:
>
> |foo=1 bar=2 baz=3
>
> and jump-char configured as follows:
>
> (global-set-key (kbd "M-m") #'jump-char-forward)
>
> I press M-m = M-m. I expect my cursor to be moved to the second equals
> sign. However, on the second M-m I'm prompted again. The docstring says:
>
> press current binding for jump-char-forward' /jump-char-backward' to reuse
> last input.
>
> so I would expect repeated presses of M-m to just search for = without
> prompting. Have I misunderstood?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lewang/jump-char/issues/16>.
>



-- 
Le

**Comment by lewang** [comment]
OIC, jupm-char-forward is ";" by default not M-m.  IIRC, I thought it more
useful to allow M-m to search for a new character.

On Thu, Jan 8, 2015 at 10:26 AM, Le Wang <l26wang@gmail.com> wrote:

> Have repro, will look into soon.
>
> On Thu, Jan 8, 2015 at 10:08 AM, Wilfred Hughes <notifications@github.com>
> wrote:
>
>> Given a buffer:
>>
>> |foo=1 bar=2 baz=3
>>
>> and jump-char configured as follows:
>>
>> (global-set-key (kbd "M-m") #'jump-char-forward)
>>
>> I press M-m = M-m. I expect my cursor to be moved to the second equals
>> sign. However, on the second M-m I'm prompted again. The docstring says:
>>
>> press current binding for jump-char-forward' /jump-char-backward' to
>> reuse
>> last input.
>>
>> so I would expect repeated presses of M-m to just search for = without
>> prompting. Have I misunderstood?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/lewang/jump-char/issues/16>.
>>
>
>
>
> --
> Le
>



-- 
Le

**Comment by Wilfred** [comment]
OK, perhaps it's worth removing the line:

> press current binding for `jump-char-forward' / `jump-char-backward' to reuse
last input.

from the docstring? I don't understand what it's saying, if it's not this feature.

**Comment by lewang** [comment]
That is the feature, though.  If you look at the variable mentioned, it's
set to ";".

On Thu, Jan 8, 2015 at 12:55 PM, Wilfred Hughes <notifications@github.com>
wrote:

> OK, perhaps it's worth removing the line:
>
> press current binding for jump-char-forward' /jump-char-backward' to reuse
> last input.
>
> from the docstring? I don't understand what it's saying, if it's not this
> feature.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lewang/jump-char/issues/16#issuecomment-69219662>.
>



-- 
Le
