### ISSUE TITLE
Advice feature. When run `set-mark-command`, open jump-char-forward.

### ISSUE THREAD

**Issue by zw963** [lewang/jump-char#21]
I think this is a better idea, When I do `set-mark-command`, What I need often is
jump to line ending, next word, next-char, the most often used command is `C-f`
`C-b`, `C-e`. those on the fly work well when jump-char-mode is active!

It seem like we does not missing anythings, But, we could add more
jump to functionality, it cool!

here is some defadvice does this
```cl
(defadvice set-mark-command (after active-jump-char activate)
  (when (region-active-p)
    (call-interactively 'jump-char-forward)))
```

Thanks.

**Comment by lewang** [comment]
Can you give more details on the use-case?  I'm not really getting it.

On Wed, Apr 27, 2016 at 10:12 AM, Billy <notifications@github.com> wrote:

> I think this is a better idea, When I do set-mark-command, What I need
> often is
> jump to line ending, next word, next-char, the most often used command is
> C-f
> C-b, C-e. those on the fly work well when jump-char-mode is active!
>
> It seem like we does not missing anythings, But, we could add more
> jump to functionality, it cool!
>
> here is some defadvice does this
>
> (defadvice set-mark-command (after active-jump-char activate)
>   (when (region-active-p)
>     (call-interactively 'jump-char-forward)))
>
> Thanks.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/lewang/jump-char/issues/21>
>



-- 
Le

**Comment by zw963** [comment]
Basically, this instead of zap-to-char, or another superset (https://github.com/thierryvolpiatto/zop-to-char)

following is a example for copy content. (with comment in it)

![recorded3061525918.gif](http://zw963.github.io/recorded3061525918.gif)

**Comment by zw963** [comment]
I notice `jump-char-isearch-map` use `jump-char-isearch-map`, this maybe cause some
shortcut conflict in some case.

**Comment by lewang** [comment]
Ok, repeat your steps without pressing C-@ first.  It already works as
expected for me.

This is because jump-char is build on isearch, which already sets the mark
before moving point.

On Wed, Apr 27, 2016 at 12:59 PM, Billy <notifications@github.com> wrote:

> I notice jump-char-isearch-map use jump-char-isearch-map, this maybe
> cause some
> shortcut conflict in some case.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/lewang/jump-char/issues/21#issuecomment-215148099>
>



-- 
Le

**Comment by zw963** [comment]
> Ok, repeat your steps without pressing C-@ first. It already works as expected for me.

if not `set-mark-command`, I could not see the highlight region, and could not copy the
region,  because M-w binding to others key. in minibuffer, it tips: `word jumb-char:`.
maybe I binding some unexepct key in isearch-mode-map.

Only first-mark and then jump is work perfect well for me.

**Comment by zw963** [comment]
It exist some conflict for me.

Because I rebinding some key in `isearch-mode-map`.

```cl
;; when enable isearch, meta f for automatically add cursor next word to isearch pattern.
;;  C-s, then meta-f have a try.
(define-key isearch-mode-map [(meta f)] 'isearch-yank-word)
```

I have to comment out this code to make `jump-char` work well with `set-mark-command`.
But, in this case, I could not use `meta f` in isearch anymore.

I try keep `(define-key isearch-mode-map [(meta f)] 'isearch-yank-word)` in isearch, and rebinding
`(define-key jump-char-isearch-map [(meta f)] 'subword-forward)`, but it not work for me.
`meta-f` still binding to `isearch-yank-word`, so I have to use `C-f` `C-b` (jump-char-process-char) to move char slowly.

I think, jump-char-mode keep all isearch-mode-map binding is a little useless.
it just need binding some `self-insert-command` to jump, and keep others 
combination command as set-mark-command does is more suitable.

**Comment by lewang** [comment]
So I recommend you start with emacs -Q to try what I propose.  You won't
see the region but will be able to act on it just the same.

On Wednesday, 27 April 2016, Billy <notifications@github.com> wrote:

> It exist some conflict for me.
>
> Because I rebinding some key in isearch-mode-map.
>
> ;; when enable isearch, meta f for automatically add cursor next word to isearch pattern.;;  C-s, then meta-f have a try.
> (define-key isearch-mode-map [(meta f)] 'isearch-yank-word)
>
> I have to comment out this code to make jump-char work well with
> set-mark-command.
> But, in this case, I could not use meta f in isearch anymore.
>
> I try keep (define-key isearch-mode-map [(meta f)] 'isearch-yank-word) in
> isearch, and rebinding
> (define-key jump-char-isearch-map [(meta f)] 'subword-forward), but it
> not work for me.
> meta-f still binding to isearch-yank-word, so I have to use C-f C-b
> (jump-char-process-char) to move char slowly.
>
> I think, jump-char-mode keep all isearch-mode-map binding is a little
> useless.
> it just need binding some self-insert-command to jump, and keep others
> combination command as set-mark-command does is more suitable.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/lewang/jump-char/issues/21#issuecomment-215288168>
>


-- 
Le

**Comment by lewang** [comment]
> I think, jump-char-mode keep all isearch-mode-map binding is a little useless

The intention is definitely to keep none of the bindings from isearch-mode-map.  Problem happens when the user customizes `isearch-mode-map` after jump-char initialized its own map.

This is not a good user experience, so I've fixed it in #22 , can @zw963 confirm?

**Comment by lewang** [comment]
Also regarding calling `set-mark-command`, I just want to make sure nothing is lost in translation - you need NEVER call this command manually.  The mark is activated when entering isearch, so all you need to do is press M-w to copy from current point to where you started jump-char.

That is to say jump-char replaces `zap-to-char` if you just press "C-w".

**Comment by zw963** [comment]
> So I recommend you start with emacs -Q to try what I propose. You won't see the region but will be able to act on it just the same.

I test. But, if not change step 3 `press r r f` with `M-f M-f`, and then press M-w, it not work well for me.

I don't know why, But I think maybe we need add a new map for jump-char-mode, and use only `self-insert-command` as jump key, and keep all others normally move hotkey. e.g. (M-f, M-b,  C-a, C-e, C-f, C-b) no change as editing in buffer,  i think this mode more useful?

**Comment by zw963** [comment]
> That is to say jump-char replaces zap-to-char if you just press "C-w".

But , it not replace normal `set-mark-command` behavior,  I still binding
`jump-char` to some keybinding I prefer, e.g. `C-;`, but, when I set mark
to highlight a region, I want to take advantage of jump-char power to
quick highlight a region, this is exact the idea what i want, `C-;` not missing
anythings, But, `C-@` is great improved by `jump-char`.

**Comment by zw963** [comment]
Maybe users habit is not same.
But, for my habit, if i want do any operation. (delete, kill, copy, delete ...), the first step
is highlight a region. so the `C-@` command is the most import command for me.

**Comment by lewang** [comment]
> when I set mark to highlight a region, I want to take advantage of jump-char power to quick highlight a region

Don't set-mark manually, jump-char always sets mark (but doesn't activate it) because of isearch.  This is how you are supposed to use Emacs.  Use the invisible "region" if you want to call it.  

Like I keep saying, even though region is not seen, you can work with it.  See below

![jump-char-m-w](https://cloud.githubusercontent.com/assets/586604/14888322/c142d2da-0d27-11e6-870e-f9852cc53138.gif)

**Comment by lewang** [comment]
> Maybe users habit is not same.

As a free (take it or leave it) piece of advice.  Your Emacs experience is smoother if you become willing to conform to Emacs instead of the other way around.  Here, Emacs is always giving you a way to save the "C-@" keystroke, but if you are insist on pressing it.

I'm not inclined to change this package to conform to people to like pressing extra keys.  ;)

**Comment by zw963** [comment]
> I'm not inclined to change this package to conform to people to like pressing extra keys. ;)

Ok, current the key is not `C-@`, it focus on this, when I open jump-char-mode with `C-;`,
And i found, `M-f M-f` is more simple for me to select just two word forward, in this case,
cursor is moving, But `M-w` not worked for me. please have a try.

Add correct `M-f M-f` and `M-w` support, not broken anything about existance. right?

**Comment by lewang** [comment]
I understand your use case now.  I'm going to think about implementation.

Can you check if #22 fixes your binding issues?

**Comment by zw963** [comment]
After a test, I found if  not first `jump to a char`, and just use `C-e, C-f, M-f ...` directly,  in all case, M-w is not work.  i think this is because mark is not correct set in this case?

**Comment by lewang** [comment]
> After a test, I found if not first jump to a char, and just use C-e, C-f, M-f ... directly, in all case, M-w is not work. 

Yes, this is expected, isearch doesn't set a mark if point is not moved before exiting isearch and all movement commands exit isearch.

**Comment by zw963** [comment]
> Can you check if #22 fixes your binding issues?

It work perfect well for my case.  if add `defadvice` in the first post,
we are free to get a more wonderful `set-mark-command`!!

Communication is expensive, What a good luck we could resolve this.

Thanks.
I no others cause,  should we merge this branch into master?

**Comment by zw963** [comment]
Hmm, After merge, I think add defadvice  to README is a good idea.

or, add a `set-mark-jump-minor-mode`, for guys like me could enable
this.

**Comment by lewang** [comment]
We can continue talking in the PR https://github.com/lewang/jump-char/pull/23

**Comment by zw963** [comment]
#23 is not work. e.g. (suppose `C-;` active jump-char-forward)

`C-; C-e M-w` not work for me.  get message:
`The mark is not set now, so there is no region`.

And, more... I think we talk about difference things.
What i say is, take advantage of jump-char, to great improved default set-mark command.
What you done is just use jump-char instead of set-mark command.

If this PR work, do you recommend let user binding jump-char directly to `C-@` or `C-SPC` ?

**Comment by zw963** [comment]
If let me to select, i think a better enhanced is support `jump-char after moving char command` to `set-mark` command.

example: (cursor at |)
```
;; This buffer is for notes you don't want to save, and for Lisp evaluation.
;; |If you want to create a file, visit that file with C-x C-f,
;; then enter the text in that file's own buffer.
```
When press  `C-@ M-f f`, we can mark region `If you want to create a `

**Comment by zw963** [comment]
Continue previous example:

When press `C-@ M-f f C-f`, we can mark region `If you want to create a f`.
That is, C-f (moving command) and f (jump command) Mixed to use.

Surely, we can exit set-mark command when jump-char-mode is exit.

example: (I suppose delete-selection-mode is enable default)

`C-@ M-f f a`, will replace `If you want to create a ` highlight region with `a`, 
and this line replace with: ``afile, visit that file with C-x C-f,``


`

**Comment by lewang** [comment]
Have you enabled the auto set-mark feature with `(setq jump-char-set-mark
t)`?

I prefer to stay from adding extra key combos that don't exit jump-char.
It's extra cognitive load that I don't want to carry.

On Thu, Apr 28, 2016 at 9:04 PM, Billy <notifications@github.com> wrote:

> Continue previous example:
>
> When press C-@ M-f f C-f, we can mark region If you want to create a f.
> That is, C-f (moving command) and f (jump command) Mixed to use.
>
> Surely, we can exit set-mark command when jump-char-mode is exit.
>
> example: (I suppose delete-selection-mode is enable default)
>
> C-@ M-f f a, will replace If you want to create a highlight region with a,
>
> and this line replace with: afile, visit that file with C-x C-f,
>
> `
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> <https://github.com/lewang/jump-char/issues/21#issuecomment-215605250>
>



-- 
Le

**Comment by zw963** [comment]
> Have you enabled the auto set-mark feature with `(setq jump-char-set-mark t)`?

No, : (

I test again, it work fine, I think when `jump-char-set-mark t`, we could use jump-char
instead of set-mark completely.

But, I think this is not convenient, in many case, we just need jump to some char,
No mark, in this case, i have to set this variable to nil first.

I think two command is better. C-@ for jump-char-set-mark t, C-; for false.

Thanks.

**Comment by lewang** [comment]
Ok, I've made 2 new commands jump-char-*-set-mark.

On Fri, Apr 29, 2016 at 1:14 PM, Billy <notifications@github.com> wrote:

> Have you enabled the auto set-mark feature with (setq jump-char-set-mark
> t)?
>
> No, : (
>
> I test again, it work fine, I think when jump-char-set-mark t, we could
> use jump-char
> instead of set-mark completely.
>
> But, I think this is not convenient, in many case, we just need jump to
> some char,
> No mark, in this case, i have to set this variable to nil first.
>
> I think two command is better. C-@ for jump-char-set-mark t, C-; for
> false.
>
> Thanks.
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> <https://github.com/lewang/jump-char/issues/21#issuecomment-215818386>
>



-- 
Le

**Comment by zw963** [comment]
Not work. Sorry.

I add some config like this:
```cl
(require 'ace-jump-mode)
(require 'jump-char)
(global-set-key [(control ?\;)] 'jump-char-forward)
(global-set-key [(control meta ?\;)] 'jump-char-backward)
(global-set-key [remap set-mark-command] 'jump-char-forward-set-mark)
```

But, When I press `C-@ M-f`, it invoke command `isearch-yank-word` ...

variable `jump-char-set-mark t` is removed, and code is work like
not enable this variable. The new change seem like break #23 .

**Comment by lewang** [comment]
I tried your config with emacs -Q and it works. Make sure you have the
right branch checked out.

On Mon, May 2, 2016 at 1:30 AM, Billy <notifications@github.com> wrote:

> Not work. Sorry.
>
> I add some config like this:
>
> (require 'ace-jump-mode)
> (require 'jump-char)
> (global-set-key [(control ?\;)] 'jump-char-forward)
> (global-set-key [(control meta ?\;)] 'jump-char-backward)
> (global-set-key [remap set-mark-command] 'jump-char-forward-set-mark)
>
> But, When I press C-@ M-f, it invoke command isearch-yank-word ...
>
> variable jump-char-set-mark t is removed, and code is work like
> not enable this variable. The new change seem like break #23
> <https://github.com/lewang/jump-char/pull/23> .
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> <https://github.com/lewang/jump-char/issues/21#issuecomment-216107654>
>



-- 
Le

**Comment by zw963** [comment]
But we still could not define new command in isearch-mode.

This problem is resolved in `create-keymap-dynamically` branch, and reappear again.

You can try add following:

```cl
(add-hook 'isearch-mode-hook 
          '(lambda ()
             (define-key isearch-mode-map [(meta f)] 'isearch-yank-word)
             ))
```

**Comment by lewang** [comment]
I'm quite unclear what's being demonstrated.  Can you discuss this in the
actual PR? https://github.com/lewang/jump-char/pull/23

Start from emacs -Q and show what actually happens vs what you expect to
happen.

On Tue, May 3, 2016 at 8:43 AM, Billy <notifications@github.com> wrote:

> But we still could not define new command in isearch-mode.
>
> This problem is resolved in create-keymap-dynamically branch, and
> reappear again.
>
> You can try add following:
>
> (add-hook 'isearch-mode-hook
>           '(lambda ()
>              (define-key isearch-mode-map [(meta f)] 'isearch-yank-word)
>              ))
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> <https://github.com/lewang/jump-char/issues/21#issuecomment-216515679>
>



-- 
Le
