### ISSUE TITLE
Symbol’s value as variable is void: lazy-highlight-face

### ISSUE THREAD

**Issue by m-cat** [lewang/jump-char#26]
I get the following error when trying to load jump-char using use-package:

`
  require: Symbol’s value as variable is void: lazy-highlight-face`

I'm using emacs 26.

**Comment by affan-salman** [comment]
For now, I've worked around this with variable aliasing:

`(defvaralias 'lazy-highlight-face 'isearch-lazy-highlight)`

Hope this helps. (-:

**Comment by m-cat** [comment]
Works for me. Thanks @lewang!
